### ISSUE TITLE
Is the ChibiOS submodule's link broken?

### ISSUE THREAD

**Issue by Martinez-Piazuelo** [e-puck2/e-puck2_main-processor#1]
https://github.com/e-puck2/e-puck2_main-processor/blob/d7dafe1ff751ce3918fe0432d490669914eab027/.gitmodules#L6

Hi.

The link of the ChibiOS submodule appears to be broken or something. After cloning the e-puck2_main-processor repo, the ChibiOS directory is empty and, therefore, the project cannot be built in eclipse. As an attempt to fix this, I went to the referenced url and searched for the submodule's commit, however, I could not find the f57f665 commit (?). As an alternative, I cloned the master branch of the referenced link and used it to replace the empty ChibiOS folder inside the cloned e-puck2_main-processor repo.  Nevertheless, the building process still outputs some errors regarding files within the ChibiOS folder.

The repository's snapshot available at the e-puck2 wiki is working, yet, the version of the firmware is not the latest one (for instance, the selector ops in the snapshot's code appear to be different than the ones explained in the wiki).

I do not know if I am missing something here, but where else could I get the latest source code of the main processor firmware?

In advance, thank you for your attention.

Juan

**Comment by gctronic** [comment]
Hi,
I just fixed the ChibiOS submodule remote URL.
I updated also the snapshot in the wiki.
